### PR TITLE
Fixed mac build machine setup script to use curl

### PR DESCRIPTION
**Pull request by basdelfos**
Fixed mac build machine setup script to use curl instead of wget (wget
is by default not available on a Mac)

### CODE REVIEW

**Comment by nathantsoi** [comment]
nice thx@ @basdelfos

**Comment by basdelfos** [comment]
The GUI app is working ok and the airmode symbols are added to the font files.
The code for the minimosd has already been implemented based on Boris' Betaflight 2.1.5 sourcecode, but I need to test it before I submit it to GitHub. Will do this later this week or weekend.

How can I generate the fontD.h and fontL.h files? It would be nice if the byte array can be generated from the corresponding font mcm file.

**Comment by ShikOfTheRa** [comment]
In other/ font editor folder should be an excel macro. I copy the text from an mcm file and paste into column. Then run the macro that comes with it. Will add into the GUI one day

**Comment by ShikOfTheRa** [comment]
I don't follow the borisb stuff from lack of time - is that also in cleanflight? What is involved?

**Comment by nathantsoi** [comment]
airmode is just in betaflight currently

**Comment by basdelfos** [comment]
That's true, it's a betaflight feature at the moment. Could be merged to cleanflight one day.
It is an additional flight mode you can switch on and off in angle, horizon or acro flight mode. It enables full PID control on zero throttle, especially for mini-quad freestyle or racing. This feature is called the best ever new feature in betaflight.

I just posted a pull request for some airmode changes I made to mwosd. It detects airmode from the FC and display's a new icon beside the flightmode icon (e.q. ACRO-AIR). Tested it today and it works perfectly. The sourcecode still works with original cleanflight and older betaflight versions.

More info about airmode: http://www.rcgroups.com/forums/showthread.php?t=2464844

**Pull request merged**
