### PR TITLE
Acro+ isn't a betaflight specific thing

### PR DESCRIPTION
**Pull request by dustin**
There are a few other firmwares that have had a mode called "Acro Plus"
for a while.  Let's support them all.

[Review on Reviewable](https://reviewable.io/reviews/shikofthera/scarab-osd/189)

### CODE REVIEW

**Comment by tracernz** [comment]
For some years before betaflight in-fact.

**Comment by ShikOfTheRa** [comment]
betaflight is the only one I've seen that seems to have MSP support for this - 
as there is close to zero bytes of sram left with some functions enabled I need to disable as much as possible. Sum of these small defines could tip it over the edge for some. It's a PITA for sure to work at this level...  Do any of the others provide it?  I'd prefer to be specific if possible. Will probably have to do a bit more of this in future :(

**Comment by dustin** [comment]
I didn't realize we could send flight mode like this. I'd like to start.

It's possible to get more feature-specific, but sprinkling target around
seems like a difficult say to do it vs. adding features by target in defs.

**Comment by ShikOfTheRa** [comment]
So going to submit a request for cleanflight in near future?

**Comment by dustin** [comment]
I don't have any interest in cleanflight.  There are videos of OpenPilot's
Acro+ from 2014.  I only started flying it myself in Tau Labs last October,
but it's been around longer than that.

I think there are a lot of ways to free up memory in the codebase while
giving people more functionality.  :)

**Comment by ShikOfTheRa** [comment]
Doh - should have remembered..! So going to put some stuff in for TAU?
Also do the Tau guys have awareness of you adding support? I don't know what other OSD can be used with Tau labs. 
I'd like to try it one day. Actually I'd like to fly one day too... Not this year - and hardly flown in 6 months :(

**Comment by dustin** [comment]
We've got a very active fork of Tau Labs called dRonin http://dronin.org/ --
that's where most of the development is taking place right now.  We've been
recommending MWOSD to our users for a while now.  Since I always run Acro+
and didn't know you could distinguish, I just updated my font for [acro] to
be acro+ (as seen in clips).  If I can distinguish, I'd like to do
something fancier, though.

Personally, I run the following combinations:

Naze32 + OSDoge on a 180mm (http://gfycat.com/LazyChubbyGrasshopper)
Naze32 + OSDoge on a 250 (recent upgrade)
Sparky 2 + microminimosd on a 150mm (
http://gfycat.com/AbsolutePerfumedAsiansmallclawedotter)
Sparky 1 + https://github.com/Brotronics/MinimOSD_MK2 on a 180mm (
http://gfycat.com/WholeExhaustedGroundhog)
Afromini + microminimosd on a 190mm (just finished doing all this last
night)

I'm hoping to build out some planes shortly.  I did have one of those mk2s
(really nice MWOSD target, btw) on one of David's mini tris, but it just
kind of fell out of the sky into a pit of corrosive marsh land.
http://gfycat.com/SlowUnlawfulAustralianshelduck

**Comment by ShikOfTheRa** [comment]
Yeah I read the dRonin stuff –so that’s the one to try J

 

Your vids are pretty mental – loved the one around the tree! And what a great play area. Its nice around here, but land like that to fly is impossible to find close by.

 

So guess adding the acro+ into dRonin is pretty simple…. Other mode options too.

 

 

I’m using baseflight for the planes – I only want normal gyro + rth for get out of jail. Let me know how get one with the plane – always interested. Been enjoying the planes more recently.

 

Where do you get the brotronics osd? Couldn’t find on google

**Comment by dustin** [comment]
I don't think the mk2 is sold anywhere.  You can get boards from OSHpark
(or wherever) and make them.  They're pretty great.

**Comment by ShikOfTheRa** [comment]
OK - cool!

**Comment by ShikOfTheRa** [comment]
Couple of questions…

For config.h
Should there be one FC entry to specify the controller? i.e..  
//#define TAULABS                   // Uncomment this if you are using the latest Tau Labs MSP Module
Or also one in there for dRonin / any otehr TL based?

I haven’t used it myself yet (with my first OP board I loved everything about OP except the acro flying characteristics so sold up and went multiwii). Not used for years so keen to try again....

Any experience with fixed wing vtail? I have a mini talon just waiting to be set up.

**Comment by dustin** [comment]
dRonin uses the TAULABS stuff.  I'm not sure if it's worth distinguishing
them at the moment.  Perhaps it should be.  They're developed mostly
independently.

I've got a lot to learn on fixed wing.  I don't even have one with a flight
controller at all at the moment.

**Comment by ShikOfTheRa** [comment]
Just trying iNav first - once have that working I'll try out dRonin. 

For this... 
Now have FC choices of DRonin and Tau Labs in config.h
Both enable the ACRO+ MSP and icon handling.

I am just about to start APM support. I think I can use dRonin for testing that. could be real useful

**Comment by ShikOfTheRa** [comment]
Dustin - will close this as it was implemented.

I now have Dronin on a board, but not on a copter yet. Bit short of hardware funds

**Comment by dustin** [comment]
Thanks.  I've got some more work to do on them myself.

**Pull request closed without merging**
