### PR TITLE
Mode 1 stick transmetter for OSD config

### PR DESCRIPTION
**Pull request by LefebvreStephane**

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Hi thanks for the contribution!!

Must admit I'm not really clear of the need here. As mode shouldn't affect
Is it more to keep the changes in line with images of stick positions etc? I guess either have to accept picture doesn't match for mode 1 or that sticks don't match.

Just a thought - would this be a simpler implementation?? Not really sure how it would impact you as mode 1 user.

/********************  RX channel rule definitions  *********************/

amend this bit in def.h ...

#elif defined TXMODE1            
  // RX CHANEL IN MwRcData table using MODE1
  #define ROLLSTICK        2
  #define PITCHSTICK       1
  #define YAWSTICK         0
  #define THROTTLESTICK    3
#else
  // RX CHANEL IN MwRcData table using MODE0
  #define ROLLSTICK        0
  #define PITCHSTICK       1
  #define YAWSTICK         2
  #define THROTTLESTICK    3
#endif

**Comment by LefebvreStephane** [comment]
hi,

I'm mode 1 transmitter, and i want control cursor with one stick (right) and value with other stick (left).

best regard

stick controle osd

**Comment by ShikOfTheRa** [comment]
Hi - your picture explains very well - I think would be strange to have cursor movements on different sticks. I also fly with a mode 1 flyer - he says he just gets used to it.. 

I had a 2nd look at my suggestion and taht would create a problem with conflict to access the menu.
So we must include.

**Comment by ShikOfTheRa** [comment]
OK - its merged.
I also moved selection to config.h - I think its important to be there
Default changed for mode 2 ! for majority...

**Pull request merged**
