### PR TITLE
PID and RC tuning page update

### PR DESCRIPTION
**Pull request by Supersopp**
Adds all the PID and RC tuning parameters supported by MSP to the PID config and RC tuning pages. This solves the PID menu bug mentioned on the roadmap. The RC tuning page also supports Cleanflight specific parameters when compiled with CLEANFLIGHT defined (should solve issue #9.) Did some refactoring on the code i touched that hopefully will not cause any issues.

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Thanks for the contribution! Would you be able to rebase this so I can have a look?

**Comment by ShikOfTheRa** [comment]
Just to add I can't merge (maybe don't know how since just started to use github..) I suspect this is as updated same menu pages

**Comment by Supersopp** [comment]
Rebased on top of current master. Just some small merge conflicts on the PID page but they where easy to resolve.

**Comment by ShikOfTheRa** [comment]
Hello. I tested today and unfortunately it doesn't work for NTSC users. To many lines for the screen. Can't see last lines or file / save exit etc...

What I was considering for future..
Display only one "Row" in PID
Use MSP PIDNAMES get to display that line + associated PID change
Also maybe boxnames to amend switches.
You would be a frigging hero if  implement that without too much memory increase. 

Also as fyi, we took some of these lesser used parts out such as POS/NAV before because so little spare memory. If new functionality added we try to optimise code memory elsewhere... its a major PITA. Especially with the structure inherited.
Also have to be very carefull of heap / stack memory free too. Ran out many times.

Target is to get it to compile with all 6 features enabled at start of config.h and debug info at end.
At moment it does as waiting to hear back about the serial changes before optimising that area.

**Comment by Supersopp** [comment]
Forgot about NTSC. Will try to change the layout or remove some of the PIDs again to make it fit. Will also see if I can reduce the memory footprint.

**Comment by ShikOfTheRa** [comment]
Yeah - its a pain in the ass. 
To make it worse, a lot of monitors cut off part or all of first and last lines... so avoid those if you can. It's the single most commented on item.....
I am now relieved because the layouts are customisable, but menus should adhere to this as the guys can't amend.
My goggles are pefect - see full screen, but my two monitors cut off most of the first / last lines. So I do get why its an issuue

**Comment by vergoh** [comment]
I gave the Supersopp changes a try with a PAL camera and Cleanflight 1.7.2. The PID config page is indeed a little bit cramped and will actually show "PID COPFIG" as title as the P for the P I D line overwrites the N letter. RC tuning page doesn't appear to have correct values. I assume that's because the layout assumes Cleanflight 1.8.x is in use with those separate roll rate and pitch rate where as 1.7.2 still had a combined roll&pitch rate.

One possible improvement could be to have some sort of NOGPS define available that would hide any GPS related output (POS, POSR, NAVR in config, speed/distance in statistics) when using a setup without GPS. Or maybe the statistics could simply not show anything that has a zero value. Sorry, if possibly a little bit off topic.

**Comment by Supersopp** [comment]
Did not notice that P, I and D overlapped the page title, but should be fixed with the latest commit.
The RC tuning page is based on Cleanflight 1.8 with separate roll and pitch rate.
Still have not fixed NTSC compatibility.

**Comment by ShikOfTheRa** [comment]
Maybe the answer is to separate out the items to a couple of pages? One for RC settings and another for GPS / nav settings.

In long term I would really like to use MSP for this...
It would be good to have all items covered within the menu. It might be quite good on memory too.

For any additions, 

Our target is to get it to compile with all of the following features enabled. It leaves enough headroom for what average user needs. Its a little over at the moment so am working to reduce memory in a few areas.

SBDIRECTION     
HORIZON
MAPMODE
GPSTIME
SPORT

**Comment by Supersopp** [comment]
Splitting the PID settings over two pages with a nav specific page, would make things easier. Would also make it easy to disable for people that do not want or need it.

I have not had much free time lately, so I have not looked into reading PID names from MSP, but it is a good idea. Would save a bit of program memory, but would need a bit more of the dynamic memory.

I also think we can save a little memory be storing the RC config in an array. makes it easier to loop through them instead of doing operations on each of them explicitly.

**Comment by ShikOfTheRa** [comment]
OK - once I've finished the current stuff am working on I'll take a look if you haven't had time. Might just be something interim for 1.4 which I want to get out pretty soon. Give a bit more time to do MSP properly in 1.5
I've had a go at memory and recovered about 1kb of flash and 150 bytes of sram.so back into position of being able to run all features which is positive

**Comment by Supersopp** [comment]
Most of the stuff i tried to fix is already in the code now, so it is probably best to close this pull request now. The other changes we have discussed are better suited as separate pull requests.

**Pull request closed without merging**
