### PR TITLE
KISS modes Turtle and RTH, messaging with 1.3RC44 and screen switch with channel

### PR DESCRIPTION
**Pull request by xaviergriffon**
- KISS mode Turtle and RTH
- Memory optimisation for serialBuffer (KISS)
- Generalization of messages from FC (code of MAVStatus)
 - KISS messaging from KISS 1.3RC44
 ~- Change EEPROM version to add the messaging position~
 - Possibility to change screen with channel on KISS
 - Channel 8,9 and 10 if present in frame
 - Get version at startup

### CODE REVIEW

**Comment by fedorcomander** [comment]
Nice!

**Comment by xaviergriffon** [comment]
Yes, I received the email, and I am replying to it.
I'm going to look to merge the message display with that of Mavlink. We will use the same position "motorArmedPosition".
I am also looking to use only the SerialBuffer and remove KissSerialBuffer.

**Comment by ShikOfTheRa** [comment]
Cool.

For serial buffer - should just be able to rename all KISSserialBuffer to serialbuffer, increase its size to what you need.

I did this with mavlink and both mavlink / MSP GUI config protocols coexist using same serialbuffer OK. I kept them separate in early developments just in case, but probability of a clash is 1 in 16 million so not too worried about the odd skipped packet at that value

**Comment by xaviergriffon** [comment]
I applied the modifications for the serialBuffer and renamed the variables of MAVStatus to generalize the display of messages from the FC.

**Comment by xaviergriffon** [comment]
I forgot, there is a small modification for the messages, we only use the first line if the message is less than 25 characters.

**Comment by ShikOfTheRa** [comment]
Great. Thanks Xavier.

I tested with Arupilot and message function is not impacted. I'll trust the KISS is all working good from your testing 👍

**Comment by ShikOfTheRa** [comment]
Would you like me to bundle the current changes up into a version release? Or do you think you will be making any further changes and wait?

**Comment by xaviergriffon** [comment]
For the moment, the KISS version supporting RTH mode and messages is not official. The only improvements, for everyone, are the Turtle mode, the configuration of the screen switch with channel and the inclusion of channels 8, 9 and 10.
Maybe @fedorcomander can tell us if there will be other features :)

**Pull request merged**
