### PR TITLE
First changes; improve cell detection and map() calls

### PR DESCRIPTION
**Pull request by Hwurzburg**
Tested. Just changed master to detect #cells at power up so batt icon
and voltage warning works at low voltages.
Also changed map() call for uniformity and altered limits to more
realistically reflect actual bat cap remaining
Next commit will change limits from compile to gui calculated.Finally, add mah bat icon compile option

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Hello - I am unable to merge this to test.
Also note, this should already be included: detect #cells at power up so batt icon and voltage warning works at low voltages.

**Comment by Hwurzburg** [comment]
Sorry,# cells are determined every loop until this change I made.
NP,will post my Fork link on RCG threads for OSD and micro for others to use

**Comment by dustin** [comment]
@Hwurzburg Can you perhaps file bugs for things that aren't working as expected?  It's a bit unclear what all you were wanting to change there.  I do see you wanted to not switch cell count while running, but also using current to show battery draining.  That does sound like a neat idea if you fly with consistent capacity.

**Comment by Hwurzburg** [comment]
all of the above WAS mergeable before a LATER pull request was merged....
and you can easily change the capacity each flight in the OSD setup screen....just like the Immersion Vortex minquad OSD (a derivative of MWOSD also)

**Pull request closed without merging**
