### PR TITLE
New platform prep

### PR DESCRIPTION
**Pull request by nathantsoi**
@shikofthera, this is almost done, but not quite there (i broke `Settings` when i moved everything), but I wanted to share as there have been lots of changes on master. I'll rebase once I get this version work (if anyone can help me fix `Settings`, that would be awesome the general idea stand:  encapsulate each component so we have more modular, testable code in hopes of taking the re-usable components and making this run on other platform (pulpino, stm32, etc.)

Other notable changes include a legit `Makefile` (only tested on Mac OS so far), but at least on mac, simply run `make` and you'll get a compiled elf and hex. Then run `make arduino-flash` with your minimosd plugged in and it will flash the device for you. On Windows, the same should be possible after installing cygwin or mingw. It also still compiles in the Arduino editor.

Also, I moved some stuff to program mem (I need to move https://github.com/ShikOfTheRa/scarab-osd/pull/216/files too) and saved quite a bit of `SRAM` space, we're using 79%, `1619` bytes on this branch

Finally, I updated the readme with debugging / simulation instructions.

While the basic ideas are there it's by no means perfect as there are still lots of globals and random interdependencies, but I figure it's better to merge now (once Settings work) so it's easier to merge other ongoing updates.

Also, btw, this is pry obvious, but for anyone who want's to help, feel free to add my upstream to your local repo and checkout my branch:

```
git remote add nathan https://github.com/nathantsoi/scarab-osd.git
git checkout new-platform-prep
```

Cheers, N

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Nathan - 
It doesn't compile for me in Arduino or allow git merge. Actually there are now so many files I can't access all of them on my laptop because it runs off the screen ! Its OK if I hook up external monitor.

I havent looked at any of the changes contained within. Might be a few days due to work...

**Comment by nathantsoi** [comment]
Strange, I just tried on a clean windows 10 install, and it seemed to compile... More changes are coming though, mostly to properly scope globals so I'll try again in a bit.

Yeah, there are a lot of files which Arduino studio doesn't seem to handle well, but as with any large project, I think having lots of well encapsulated classes should help make this much more maintainable and portable going forward. Plus, with the makefile its possible to use eclipse or some other real editor for development. I'm using vim + make

**Comment by truglodite** [comment]
Compiles clean with Arduino IDE 1.6.8 on win10 for me. I am too busy to test just yet, but the space savings and 32bit mcu are very attractive. Thanks Nathan... hope this works out.

**Comment by jflyper** [comment]
@nathantsoi , just a quick comment:
Funny, the current master compiles with 1499 bytes of RAM (versus new-platform-prep at 1638).
Did you consider #211, too?

**Comment by jflyper** [comment]
@ShikOfTheRa , @nathantsoi ,
Any pointer to previous discussion on strategy for the "new platform support" is greatly appreciated.

**Comment by nathantsoi** [comment]
yeah, sorry, this is still in-progress. it compiles and shows "no data" for
me, but i think some settings are still messed up. i havent had much time
to continue on this, hopefully i will in a bit though.

thx for testing @truglodite

you're right @jflyper, #211 is still a todo, plus, generally eliminating
duplicate data would be a big win

i dont think there was previous discussion, this is just me trying to
cleanup. turns out the code was much more of a mess than I originally
anticipated. idk, but if it isn't straightforward to debug why this isn't
working as expected, it might be worth starting from scratch as there is
lots of logic/data I don't know what to do with, e.g. the 3 different
"armed" variables, etc.

any help would be much appreciated!

**Comment by tracernz** [comment]
Getting this building with a Makefile would be super nice. Would help a lot with d-ronin/d-ronin#899!

**Comment by nathantsoi** [comment]
closing this for now. the makefile building part works great if someone wants to pull it into the main project.

**Pull request closed without merging**
