### PR TITLE
Msp write functions

### PR DESCRIPTION
**Pull request by Supersopp**
Tried to clean up the MSP writes. Reduced a lot of repetition in the code, making it easier to read and saved 458 bytes of program memory. It may be slightly slower and use a bit more dynamic memory due to additional function calls, but I have not tested this. Everything i have tried seems to function as expected, but I can not guarantee that I have not broken anything.

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Like the look of this. Some great memory savings. Will try out in morning

**Comment by ShikOfTheRa** [comment]
Looks great - a big improvement.
Ran through some tests and looks good to me. Just one byte of sram. 

Only one issue - it will not let me merge... I'm not that familiar with how to use github for that sort of thing unless it gives me the green button! Any guidance there how I can do that?

**Comment by Supersopp** [comment]
Rebased on top of latest changes on Shiki-R1.4-dev.  It says it can be automatically merged now, so you should be able to merge. 

I think GIt got a little confused as I removed some empty lines at the end of Serial.ino. This could also have been resolved by a manual merge.

**Comment by ShikOfTheRa** [comment]
OK all done. Brill - thanks...
I'll have to google the manual merge. tried following the help on github and that cli stuff, but didn't seem to tell me anything...

**Pull request merged**
