### PR TITLE
Serial.ino tidying

### PR DESCRIPTION
**Pull request by jflyper**
Did some extensive tidying of serialMenuCommon(), mainly for readability in following areas:

(1) Avoid extra “`if (ROW/COL)`” execution.
(2) Define and use macros for common operations: `ReverseSetting()`, `ModifySetting()` and `ModifySetting16()`.
(3) Use “`+=`“ syntax sugar.
(4) Indentation and leading white space fix.

You may not like the formatting, in which case, just say noop:)

Did try to reduce some code by replacing ignored `read8/16()`s by `skip8/16()` macros also.

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
I agree it looks much better - 
but I am seeing an extra 93 bytes of nvram used. That's quite an impact to improve readability.
( I use memcheck / fixedwing_BF / scrolling bars features enabled as worst case frequently used benchmark for a config that needs to run. We would loose 30% of available nvram which is pretty significant). 
Anything can do to reduce? 

Formatting fine with me. Terse is very readable.. like the style.

At some point I was intending to look at the menu's further to see if can use a struct format instead of if/case. Not sure if feasible for all options though.

**Comment by jflyper** [comment]
@ShikOfTheRa 
Wow, I didn't notice the increase. AMOF, the last check I did came up with -30 bytes in flash and +/-0 in ram.

Let me look into it.

**Comment by ShikOfTheRa** [comment]
Might be the arduino / compiler version again
I did see 0 in the ram.

**Comment by jflyper** [comment]
@ShikOfTheRa
You are right.
Started from a fresh fork from current ShikOfTheRa/master:

type  |1.0.5 | 1.6.8 (flash) | 1.6.8 (ram)
-------|--------|----------|--------------
without  |  30,566 | 26,880 | 1,690
with | 30,654 | 26,850 | 1,690
            |      +88 |       -30 |        0

I couldn't get the 94 bytes you mentioned, but it's pretty close.
And since the number 88 is about same as the number of '`case`'s in the new code, my guess is that 1.0.5 is some how  generating one extra byte per each `case`.

I'll look further into the case...

**Comment by ShikOfTheRa** [comment]
Wow that's some significant nvram savings. Huge. Far more than I would have guessed. 

Maybe its time to poll how many people need to run 1.0.x 


Nice pun BTW :)

**Comment by jflyper** [comment]
@ShikOfTheRa 
> Maybe its time to poll how many people need to run 1.0.x

Yeah, I was just re-thinking about the proposal to leave 1.0.x behind. As a matter of fact, this came to me immediately after (next day or the day after) we had this discussion in the nathan's PR, when I found out 1.0.6 is no longer executable on my Mac running El Capitan (comes with Java 8), without installing older Java 7 (I'm not even sure if this caused some security issues or not ;-<)

So 1.0.x is no longer an easy install and use tool for some people already.

>Nice pun BTW :)

I didn't notice that either!

**Pull request merged**
