### PR TITLE
Submenu for KISS configurations

### PR DESCRIPTION
**Pull request by xaviergriffon**
Use a submenu because otherwise it would be necessary to completely reconfigure the card or send x commands.
Each category has its order for its configuration.

### CODE REVIEW

**Comment by xaviergriffon** [comment]
As explained in the commit, creating a submenu for KISS configuration to avoid sending multiple commands or global configuration.
I will try to implement other submenu but I wanted to have a validation of the principle and the graphic part.

**Comment by ShikOfTheRa** [comment]
I am on holiday for  a little while - I will look as soon as I can. Does it only impact KISS? I am sur eit is OK

**Comment by xaviergriffon** [comment]
The changes are encapsulated for KISS or KISSGPS compilations.
The menu and its submenus are KISS specific, the only existing menu where I had to make changes is the PID to suppress the injection of the previous COMMIT. But again, it was KISS brick.

For security, I made a compilation test of all the platforms that happened successfully.

Good holidays ;)

**Comment by ShikOfTheRa** [comment]
OK. Cool. 

Will changes be backwards compatible with older kiss versions or will they have to update to a minimum version level. It is no problem either option.
All common builds are also tested in here:
https://github.com/ShikOfTheRa/scarab-osd/blob/master/platformio.ini

**Comment by xaviergriffon** [comment]
I don't know the exact version, just that it is compatible with the KISS FC V1 and KISS versions dating less than 3 years. LUA scripts for OpenTX and KISSOSD have been using these commands for a long time.
For the GPS, it will indeed specify the version.

I discovered platformio with this project, too cool ;) I develop and perform compilation tests for other platforms with.

**Pull request merged**
