### PR TITLE
Can put mah/km?

### PR DESCRIPTION
**Pull request by Ansarida**
Hii i want do long range for quad copter i relly need mah/km

means calculation for mah per kilometer is been used

### CODE REVIEW

**Comment by ShikOfTheRa** [comment]
Think this is in error?

**Comment by Ansarida** [comment]
not and error but add more function

**Comment by ShikOfTheRa** [comment]
The only changes I see in here are for travis - no new code?

Do any of the following give you what you need. The last one appears very similar

/********************       Power / efficiency display Settings         ************************/
#define DISPLAYWATTS                // Enable this to display Watts (if Watts selected in layouts). Select one of WATTS/MAHMIN/EFFICIENCY
//#define DISPLAYEFFICIENCY         // Enable this to display Watts/KMh or Mph for efficiency (if Watts selected in layouts). Select one of WATTS/MAHMIN/EFFICIENCY
//#define DISPLAYMAHMIN             // Enable this to display average mAh/minKMh (if Watts selected in layouts). Select one of WATTS/MAHMIN/EFFICIENCY

**Comment by Ansarida** [comment]
ic thank u sir... 
mAh/minKMh<- this can do mah/km ?

but what is minKMh means?

**Comment by ShikOfTheRa** [comment]
We had many discussions and email ove rthis and this was end result.:

Efficiency - instantaneous efficiency value Watts/KMh (this is most common used for fixedwing and similar to other FC)
MAHMIN - average of flight - MAh used over minutes flown.

Happy to add any extra options

**Comment by ShikOfTheRa** [comment]
Hi - I am going to close this Pull request as there is no valid code associated.
If you want an additional efficiency option please raise it as an issue - detailing exactly what you require.

Thanks!

**Comment by Ansarida** [comment]
thank u sir.... this is superb support...

**Pull request closed without merging**
